require: rubocop-rspec

AllCops:
  EnabledByDefault: true
  TargetRubyVersion: 2.2

Metrics/BlockLength:
  Exclude:
    - lox.gemspec
    - spec/**/*_spec.rb

Style/Copyright:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/DocumentationMethod:
  Enabled: false
