require: rubocop-rspec

AllCops:
  DisplayCopNames: true
  EnabledByDefault: true
  TargetRubyVersion: 2.4

Metrics/BlockLength:
  Exclude:
    - lox.gemspec

Style/Copyright:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/DocumentationMethod:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/MethodCallWithArgsParentheses:
  Enabled: false

Style/MissingElse:
  Enabled: false
