language: ruby
rvm:
  - 2.5
  - 2.4
  - 2.3
  - 2.2
addons:
  code_climate:
    repo_token:
      secure: hzkkfSIVGAsI0100Eca0u9vRoQaqO9hkLE+Q7geAVBcnFmiHj2ukNX2BoHr1AQ4OAYNuobNVUbFYbuwDGoLNi8Eocoo1ZQblM4rBAKm3QTe/NmRSwJfdqH716Bt7ttfBz4DIsCm+POKwdnRT820ltMS5pBBz3WEUPRS54mvbtd63I5gUuf761eO8n9mCYIuRSLVU/oFzz0C7eSapzDxyE0UQ46647WLbFOE01R+DBAlHTI1Ua2j1fAxxiktYf/mI+B9842I61gsWCh50oBw55CxgsX+IzrIgV/NcCzaGBRPDy/8glecNzgB4hRwBHT9LSMe6SzKjmVcVblHUTfffgrHUi+NKL67cSnZgNaj9JHHDQIeNBswRR7Z0duMo0/0nbg2EYjlL2QLhDrhzwFZVLQZX/XnKx6wckG3KFCNVjjPXg07xV4tPLtEOBmW20qG93PBG5vbkZZh6G4VwaNj543TNfaaCIn5Gj0TxA0bZ/Tk+dUpHZ+wTGJn4nS50rybceJHfRT7aiFG6lzIvzBMVyimWbliJfivKdtjPCi27Yip+g4p6TecSkOfTDlYYOfclsIkg8O0Fbu7zirqyk6KiBxK4ZvKIYYXgVZRCU2d6xrGMXwHPF9KgqtZLcxCLjdMJkIjFlp4SOiCWsD2QKZ420eKDPPEDepFFMvNoWNf6YlE=
before_install:
  - gem update --system
  - gem install bundler
after_success:
  - bundle exec codeclimate-test-reporter
